include: package:flutter_lints/flutter.yaml
  
analyzer:
  plugins:
    - riverpod_lint

plugins:
  riverpod_lint: ^3.0.0

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

