// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NTBW2PjwpbrMzv2e1DB4b8nXVwMYaEo',
    appId: '1:1012305295180:web:b8591aa0ba8913dfe801e9',
    messagingSenderId: '1012305295180',
    projectId: 'uglian-5caf0',
    authDomain: 'uglian-5caf0.firebaseapp.com',
    storageBucket: 'uglian-5caf0.firebasestorage.app',
    measurementId: 'G-6QV668J2E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS2ma0jQF_4HX51meDQH4rYdBWn7z-YUQ',
    appId: '1:1012305295180:android:0c8a64dfc75926b5e801e9',
    messagingSenderId: '1012305295180',
    projectId: 'uglian-5caf0',
    storageBucket: 'uglian-5caf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrrDlwskq1SE4xGG6IjEZCTbjm_qAYWE',
    appId: '1:1012305295180:ios:c11723424a3b9552e801e9',
    messagingSenderId: '1012305295180',
    projectId: 'uglian-5caf0',
    storageBucket: 'uglian-5caf0.firebasestorage.app',
    iosBundleId: 'com.example.uglian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrrDlwskq1SE4xGG6IjEZCTbjm_qAYWE',
    appId: '1:1012305295180:ios:c11723424a3b9552e801e9',
    messagingSenderId: '1012305295180',
    projectId: 'uglian-5caf0',
    storageBucket: 'uglian-5caf0.firebasestorage.app',
    iosBundleId: 'com.example.uglian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0NTBW2PjwpbrMzv2e1DB4b8nXVwMYaEo',
    appId: '1:1012305295180:web:dcaed5d8190ac2fbe801e9',
    messagingSenderId: '1012305295180',
    projectId: 'uglian-5caf0',
    authDomain: 'uglian-5caf0.firebaseapp.com',
    storageBucket: 'uglian-5caf0.firebasestorage.app',
    measurementId: 'G-3FT2K9QRJM',
  );
}
